---
name: Test-Most
version: 0.11
author:
  - 'Curtis Poe <ovid@cpan.org>'
abstract: Most commonly needed test functions and features.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Deep: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::Harness: 3.07
  Test::More: 0
  Test::Warn: 0.1
  perl: 5.006
provides:
  Test::Most:
    file: lib/Test/Most.pm
    version: 0.11
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
