---
abstract: unknown
author:
  - unknown
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Most
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/Ovid/test--most
version: 0.32
