---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Most
no_index:
  directory:
    - t
    - inc
requires:
  Exception::Class: '1.14'
  Test::Deep: '0.106'
  Test::Differences: '0.61'
  Test::Exception: '0.31'
  Test::Harness: '3.21'
  Test::More: '0.88'
  Test::Warn: '0.23'
resources:
  repository: https://github.com/Ovid/test--most
version: '0.34'
